#Print the chorus from your favourite  song in a single print statement, using  line breaks escapes.
print("Take me down to the paradise city Where the grass is green and the girls are pretty Take me home oh, won't you please take me home Take me down to the paradise city Where the grass is green and the girls are pretty Take me home oh, won't you please take me home")
print("\"Joey doesn't share food!\"")
print("a linear sequence of characters, words, or other data.")
print("integers are zero, positive or negative whole numbers without a fractional part and having unlimited precision")
print("converts a number stored in a string or integer into a floating point number, or a number with a decimal point.")
print(543/3)
print(543%3)
print(1000%9)
print(434//10)
print(3%2)
print(5%5)